### ISSUE TITLE
Code implement of other datasets

### ISSUE THREAD

**Issue by JhuoW** [jiyangbai/TaGSim#1]
Hi, 
Could you provide the code implementation of other datasets?

**Comment by jiyangbai** [comment]
Hello, we have updated the code implementations on other datasets.

**Comment by jiyangbai** [comment]
> Hi,
> Could you provide the code implementation of other datasets?

**Comment by jiyangbai** [comment]
> Hi,
> Could you provide the code implementation of other datasets?

Hello, we have updated the code implementations on other datasets.
